name: Daily Random Commit

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 UTC
  workflow_dispatch:      # Allows manual run from GitHub

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python random_commit.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add daily_commit.txt
        git commit -m "🤖 Daily random commit" || echo "No changes to commit"
        git push
